language: objective-c
sudo: false

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail && xcodebuild -project OHHTTPStubs/OHHTTPStubs.xcodeproj -scheme "OHHTTPStubs iOS StaticLib" -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - set -o pipefail && xcodebuild -project OHHTTPStubs/OHHTTPStubs.xcodeproj -scheme "OHHTTPStubs Mac Framework" -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - set -o pipefail && xcodebuild -project OHHTTPStubs/OHHTTPStubs.xcodeproj -scheme "OHHTTPStubs iOS Framework" -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO analyze | xcpretty -c